//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaMinhPhuoc_QLTaiKhoan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string userName { get; set; }
        public string ownerName { get; set; }
        public string email { get; set; }
        public string passWord { get; set; }
        public int roleID { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
